### ISSUE TITLE
continue (`X.`) continues indiscriminately

### ISSUE THREAD

**Issue by digital-carver** [lmendo/MATL#11]
Hi! Is it intended that continue (`X.`) goes to the next iteration without checking the stack? 

The manual says "the loop proceeds with the next iteration, if any" - the "if any" part makes it sound like it should check the stack like the loop usually does, and go the next iteration only if it's truthy. That's the behaviour I'd expect from other languages too - `continue` means skip the rest of the loop, but do check the loop condition again. It seems like that's not the behaviour in MATL, from some testing: 

**Without continue**
```
octave:1> matl 'F T X` X# '
/-------
STACK{1} = 

0

-------/
```

**With continue at the end of loop**

```
octave:2> matl 'F T ` X# X.'
/-------
STACK{1} = 

0

-------/
/-------
STACK{1} = 

0

-------/
/-------
STACK{1} = 

0

-------/
```
(output goes on indefinitely, loop doesn't terminate)

**Comment by lmendo** [comment]
Thank you for catching this! Yes, it should be fixed. I think I know what I need to change in the compiler to achieve the desired behaviour, but I don't have the time now. I'll do it within the next few days. This affects both "while" and "do while" loops

**Comment by lmendo** [comment]
This should be fixed now with the latest [commit](https://github.com/lmendo/MATL/commit/f0400d410c5ec773ae921e50f2416f3bcc393219). It can be tested in MATL Online:

https://matl.io/?code=F+T+%60+X%23+X.&inputs=&version=f0400d41

Thanks again!
