### ISSUE TITLE
Examples for porting MATLAB code to MATL

### ISSUE THREAD

**Issue by dennisjaheruddin** [lmendo/MATL#2]
First of all, nice project!

In the introduction I read that one can get started in a few minutes, so I decided to try it a bit, but it is actually not that easy to get started.

When browsing the doc, I see a few examples of MATL code, and their MATLAB equivalent, but without much help on turning MATLAB code into MATL code.

Here is what I tried:

Getting the sum of numbers 2:10

2:10 % This is easy!
sum(2:10) %Hmm too bad
s(2:10) %Well this is the function, now how do I call it
...
2:10s %Yay
Input: 10 code: :s %Ok, so it is easy to use one input
inputs: 2 and 10 code: :s %Ok I guess I don't know how to use two

After this I tried to use datestr, but I basically failed to make it do anything. (First attempt was to replicate a simple datestr(1)).

So my conclusion:
I think this will help a lot for code golf, but a number of examples on how to get from MATLAB to MATL would be very helpful :)

**Comment by lmendo** [comment]
Hello, Dennis! Thanks for your interest in the project and for your nice comments. Yes, I may have been a little optimistic when saying "within minutes". On the other hand, I said "to _start_ programming in MATL" :-P

The most important difference is that MATL is stack-based and uses postfix notation for functions. So your `2:10s` means "push 2:10 onto the stack, and then apply function `s` on that" (`s` takes one input from the stack by default). If you wanted to sum along the first dimension (admittedly not very useful for this array) you could use `2:10 1 2$s`. `2$` means that `s` should take two inputs: so `sum(2:10, 1)`. Or, shorter: `2:10H$1s`. This uses `H`, which is a like a·variable (actually a "clipboard") which contains `2` by default. For some functions there is an alternative form. For example, `Xs` is like `s` along the first dimension. So you could use `2:10Xs` to sum along the first dim. That happens for a few others. For example, `u` is `unique` (with `'stable'` flag by default); `Xu`  is `unique(..., 'rows', ...)` (also with `'stable'` by default).

Let me know any specific question you may have. I'd be very happy to answer them (if I can). You can also ping me at the Matlab chatroom (http://chat.stackoverflow.com/rooms/81987/matlab-and-octave) or at the 19th byte chat room (https://chat.stackexchange.com/rooms/240/the-nineteenth-byte). Also, this answer may give you an idea of some of MATL's fearures: http://codegolf.stackexchange.com/a/76535/36398

**Comment by suever** [comment]
Just as an additional follow-up to this, @lmendo has created a [MATL-specific chatroom](https://chat.stackexchange.com/rooms/39466/matl) if you have any questions.
