### ISSUE TITLE
Support descending arrays with the colon operator

### ISSUE THREAD

**Issue by DJMcMayhem** [lmendo/MATL#4]
The colon operator should be able to make ascending and descending arrays. For example, this:

```
4:2
```

should push the array

```
[4 3 2]
```

Rather than just pushing an empty array, like it does now. This is possible right now with:

```
2:4P
```

But this way is one byte longer and less intuitive.

**Comment by lmendo** [comment]
As commented in the chat room, the fact that `4:2` gives `[]` is consistent with Matlab's behaviour. Of course that consistency could be sacrificed. But I think there are some reasons in favour of the current behaviour. `a:b` with `a` and `b` numeric literals means "array formed by all numbers starting at `a` and adding `1` until exceeding `b`. With that interpretation, `4:2`  should give `[]`.

Perhaps the proposed modification could be applied to the _literal_ version of `:` (`4:2`), but not to the _function_ `:` (`4 2 &:`). In the literal version, the programmer knows which numbers are being used and how they will be interpreted, whereas in the function form the inputs are not known at programming time
